"""use BIGINT for course_media_id on tasks and sub_video_tasks

Revision ID: 30aa2810635a
Revises: 82592e0a0570
Create Date: 2025-08-13 16:57:15.203244

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30aa2810635a"
down_revision: Union[str, Sequence[str], None] = "82592e0a0570"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_material_analyses_task_original_url"),
        table_name="material_analyses",
        schema="textloom_core",
    )
    op.alter_column(
        "sub_video_tasks",
        "course_media_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        comment="视频合成服务的媒体ID（使用BIGINT以兼容大数ID）",
        existing_comment="视频合成服务的媒体ID",
        existing_nullable=True,
        schema="textloom_core",
    )
    op.drop_index(
        op.f("idx_sub_video_tasks_sub_task_id"),
        table_name="sub_video_tasks",
        schema="textloom_core",
    )
    op.alter_column(
        "tasks",
        "course_media_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        comment="视频合成服务的媒体ID（使用BIGINT以兼容大数ID）",
        existing_comment="视频合成服务的媒体ID",
        existing_nullable=True,
        schema="textloom_core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "course_media_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        comment="视频合成服务的媒体ID",
        existing_comment="视频合成服务的媒体ID（使用BIGINT以兼容大数ID）",
        existing_nullable=True,
        schema="textloom_core",
    )
    op.create_index(
        op.f("idx_sub_video_tasks_sub_task_id"),
        "sub_video_tasks",
        ["sub_task_id"],
        unique=True,
        schema="textloom_core",
    )
    op.alter_column(
        "sub_video_tasks",
        "course_media_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        comment="视频合成服务的媒体ID",
        existing_comment="视频合成服务的媒体ID（使用BIGINT以兼容大数ID）",
        existing_nullable=True,
        schema="textloom_core",
    )
    op.create_index(
        op.f("idx_material_analyses_task_original_url"),
        "material_analyses",
        ["task_id", "original_url"],
        unique=True,
        schema="textloom_core",
    )
    # ### end Alembic commands ###
