"""add context fields to media_items

Revision ID: 3737e96ea445
Revises: 8f1c2d9a7b21
Create Date: 2025-08-15 20:32:17.047492

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3737e96ea445"
down_revision: Union[str, Sequence[str], None] = "8f1c2d9a7b21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_material_analyses_task_original_url"),
        table_name="material_analyses",
        schema="textloom_core",
    )
    op.add_column(
        "media_items",
        sa.Column("context_before", sa.Text(), nullable=True, comment="前一自然段落"),
        schema="textloom_core",
    )
    op.add_column(
        "media_items",
        sa.Column("context_after", sa.Text(), nullable=True, comment="后一自然段落"),
        schema="textloom_core",
    )
    op.add_column(
        "media_items",
        sa.Column(
            "surrounding_paragraph", sa.Text(), nullable=True, comment="所在段落全文"
        ),
        schema="textloom_core",
    )
    op.add_column(
        "media_items",
        sa.Column("caption", sa.Text(), nullable=True, comment="图注/alt文本"),
        schema="textloom_core",
    )
    op.add_column(
        "media_items",
        sa.Column(
            "position_in_content",
            sa.Integer(),
            nullable=True,
            comment="在全文中的位置索引",
        ),
        schema="textloom_core",
    )
    op.drop_index(
        op.f("idx_sub_video_tasks_sub_task_id"),
        table_name="sub_video_tasks",
        schema="textloom_core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_sub_video_tasks_sub_task_id"),
        "sub_video_tasks",
        ["sub_task_id"],
        unique=True,
        schema="textloom_core",
    )
    op.drop_column("media_items", "position_in_content", schema="textloom_core")
    op.drop_column("media_items", "caption", schema="textloom_core")
    op.drop_column("media_items", "surrounding_paragraph", schema="textloom_core")
    op.drop_column("media_items", "context_after", schema="textloom_core")
    op.drop_column("media_items", "context_before", schema="textloom_core")
    op.create_index(
        op.f("idx_material_analyses_task_original_url"),
        "material_analyses",
        ["task_id", "original_url"],
        unique=True,
        schema="textloom_core",
    )
    # ### end Alembic commands ###
