"""add media_items.resolution

Revision ID: 82592e0a0570
Revises: b50e8fba3c88
Create Date: 2025-08-12 16:57:00.992388

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82592e0a0570"
down_revision: Union[str, Sequence[str], None] = "b50e8fba3c88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_material_analyses_task_original_url"),
        table_name="material_analyses",
        schema="textloom_core",
    )
    op.add_column(
        "media_items",
        sa.Column("resolution", sa.String(length=20), nullable=True, comment="分辨率"),
        schema="textloom_core",
    )
    op.drop_index(
        op.f("idx_sub_video_tasks_sub_task_id"),
        table_name="sub_video_tasks",
        schema="textloom_core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_sub_video_tasks_sub_task_id"),
        "sub_video_tasks",
        ["sub_task_id"],
        unique=True,
        schema="textloom_core",
    )
    op.drop_column("media_items", "resolution", schema="textloom_core")
    op.create_index(
        op.f("idx_material_analyses_task_original_url"),
        "material_analyses",
        ["task_id", "original_url"],
        unique=True,
        schema="textloom_core",
    )
    # ### end Alembic commands ###
