"""sync models to db

Revision ID: 8b9d6ff77653
Revises: b15222e11ab9
Create Date: 2025-08-21 18:28:32.597709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9d6ff77653'
down_revision: Union[str, Sequence[str], None] = 'b15222e11ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='全名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='哈希密码'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='是否超级用户'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='是否验证邮箱'),
    sa.Column('preferences', sa.JSON(), nullable=True, comment='用户偏好设置'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='时区'),
    sa.Column('language', sa.String(length=10), nullable=True, comment='语言偏好'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('token_version', sa.Integer(), nullable=True, comment='Token版本号，用于刷新时废除旧token'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='textloom_core'
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False, schema='textloom_core')
    op.create_index('ix_users_username', 'users', ['username'], unique=False, schema='textloom_core')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('jti', sa.String(length=36), nullable=False, comment='JWT ID，用于撤销'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='Token哈希值'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('is_revoked', sa.Boolean(), nullable=True, comment='是否已撤销'),
    sa.Column('device_info', sa.String(length=200), nullable=True, comment='设备信息'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.ForeignKeyConstraint(['user_id'], ['textloom_core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti'),
    schema='textloom_core'
    )
    op.create_index('ix_refresh_tokens_jti', 'refresh_tokens', ['jti'], unique=False, schema='textloom_core')
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False, schema='textloom_core')
    op.drop_index(op.f('idx_material_analyses_task_original_url'), table_name='material_analyses', schema='textloom_core')
    op.drop_index(op.f('idx_sub_video_tasks_sub_task_id'), table_name='sub_video_tasks', schema='textloom_core')
    # First, move existing creator_id values to legacy_creator_id
    op.add_column('tasks', sa.Column('legacy_creator_id', sa.String(length=100), nullable=True, comment='遗留创建者ID（向后兼容）'), schema='textloom_core')
    
    # Update legacy_creator_id with current creator_id values
    op.execute("UPDATE textloom_core.tasks SET legacy_creator_id = creator_id WHERE creator_id IS NOT NULL")
    
    # Drop the original creator_id column
    op.drop_column('tasks', 'creator_id', schema='textloom_core')
    
    # Add the new creator_id column as UUID type
    op.add_column('tasks', sa.Column('creator_id', sa.UUID(), nullable=True, comment='创建者ID'), schema='textloom_core')
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'], source_schema='textloom_core', referent_schema='textloom_core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', schema='textloom_core', type_='foreignkey')
    # Drop the UUID creator_id column
    op.drop_column('tasks', 'creator_id', schema='textloom_core')
    # Add back the VARCHAR creator_id column 
    op.add_column('tasks', sa.Column('creator_id', sa.String(length=100), nullable=True, comment='创建者ID'), schema='textloom_core')
    # Restore creator_id values from legacy_creator_id
    op.execute("UPDATE textloom_core.tasks SET creator_id = legacy_creator_id WHERE legacy_creator_id IS NOT NULL")
    op.drop_column('tasks', 'legacy_creator_id', schema='textloom_core')
    op.create_index(op.f('idx_sub_video_tasks_sub_task_id'), 'sub_video_tasks', ['sub_task_id'], unique=True, schema='textloom_core')
    op.create_index(op.f('idx_material_analyses_task_original_url'), 'material_analyses', ['task_id', 'original_url'], unique=True, schema='textloom_core')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens', schema='textloom_core')
    op.drop_index('ix_refresh_tokens_jti', table_name='refresh_tokens', schema='textloom_core')
    op.drop_table('refresh_tokens', schema='textloom_core')
    op.drop_index('ix_users_username', table_name='users', schema='textloom_core')
    op.drop_index('ix_users_email', table_name='users', schema='textloom_core')
    op.drop_table('users', schema='textloom_core')
    # ### end Alembic commands ###
