"""add original_url field to material_analyses and media_items

Revision ID: b50e8fba3c88
Revises: c9c7a666f577
Create Date: 2025-08-12 16:09:05.272359

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b50e8fba3c88"
down_revision: Union[str, Sequence[str], None] = "c9c7a666f577"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add original_url columns as nullable first
    op.add_column(
        "material_analyses",
        sa.Column("original_url", sa.Text(), nullable=True, comment="原始URL"),
        schema="textloom_core",
    )
    op.add_column(
        "media_items",
        sa.Column("original_url", sa.Text(), nullable=True, comment="原始URL"),
        schema="textloom_core",
    )

    # Step 2: Migrate existing data - copy file_url to original_url
    from sqlalchemy import text

    connection = op.get_bind()

    # Copy file_url to original_url for material_analyses
    connection.execute(
        text(
            """
        UPDATE textloom_core.material_analyses 
        SET original_url = file_url 
        WHERE original_url IS NULL
    """
        )
    )

    # Copy file_url to original_url for media_items
    connection.execute(
        text(
            """
        UPDATE textloom_core.media_items 
        SET original_url = file_url 
        WHERE original_url IS NULL
    """
        )
    )

    # Step 3: Make original_url NOT NULL after data migration
    op.alter_column(
        "material_analyses", "original_url", nullable=False, schema="textloom_core"
    )
    op.alter_column(
        "media_items", "original_url", nullable=False, schema="textloom_core"
    )

    # Step 4: Update file_url column comments and make nullable
    op.alter_column(
        "material_analyses",
        "file_url",
        existing_type=sa.TEXT(),
        nullable=True,
        comment="云存储URL",
        existing_comment="文件URL",
        schema="textloom_core",
    )
    op.alter_column(
        "media_items",
        "file_url",
        existing_type=sa.TEXT(),
        nullable=True,
        comment="云存储URL",
        existing_comment="文件URL",
        schema="textloom_core",
    )

    # Step 5: Update constraints and indexes
    op.drop_index(
        op.f("idx_material_analyses_task_file"),
        table_name="material_analyses",
        schema="textloom_core",
    )
    op.drop_constraint(
        op.f("uq_material_analyses_task_file"),
        "material_analyses",
        schema="textloom_core",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_material_analyses_task_original_url",
        "material_analyses",
        ["task_id", "original_url"],
        schema="textloom_core",
    )

    # Add scenes column to script_contents
    op.add_column(
        "script_contents",
        sa.Column("scenes", sa.JSON(), nullable=True, comment="场景列表"),
        schema="textloom_core",
    )
    op.drop_index(
        op.f("idx_sub_video_tasks_sub_task_id"),
        table_name="sub_video_tasks",
        schema="textloom_core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_sub_video_tasks_sub_task_id"),
        "sub_video_tasks",
        ["sub_task_id"],
        unique=True,
        schema="textloom_core",
    )
    op.drop_column("script_contents", "scenes", schema="textloom_core")
    op.alter_column(
        "media_items",
        "file_url",
        existing_type=sa.TEXT(),
        nullable=False,
        comment="文件URL",
        existing_comment="云存储URL",
        schema="textloom_core",
    )
    op.drop_column("media_items", "original_url", schema="textloom_core")
    op.drop_constraint(
        "uq_material_analyses_task_original_url",
        "material_analyses",
        schema="textloom_core",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_material_analyses_task_file"),
        "material_analyses",
        ["task_id", "file_url"],
        schema="textloom_core",
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_material_analyses_task_file"),
        "material_analyses",
        ["task_id", "file_url"],
        unique=True,
        schema="textloom_core",
    )
    op.alter_column(
        "material_analyses",
        "file_url",
        existing_type=sa.TEXT(),
        nullable=False,
        comment="文件URL",
        existing_comment="云存储URL",
        schema="textloom_core",
    )
    op.drop_column("material_analyses", "original_url", schema="textloom_core")
    # ### end Alembic commands ###
