"""Add download and upload status fields to media_items

Revision ID: b7e36c1ff1a7
Revises: f90ca5d807de
Create Date: 2025-11-20 17:06:37.287163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e36c1ff1a7'
down_revision: Union[str, Sequence[str], None] = 'f90ca5d807de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_material_analyses_task_original_url'), table_name='material_analyses', schema='textloom_core')
    op.add_column('media_items', sa.Column('local_path', sa.Text(), nullable=True, comment='本地文件路径'), schema='textloom_core')
    op.add_column('media_items', sa.Column('cloud_url', sa.Text(), nullable=True, comment='云存储URL(另一个)'), schema='textloom_core')
    op.add_column('media_items', sa.Column('download_status', sa.String(length=20), nullable=True, comment='下载状态'), schema='textloom_core')
    op.add_column('media_items', sa.Column('upload_status', sa.String(length=20), nullable=True, comment='上传状态'), schema='textloom_core')
    op.add_column('media_items', sa.Column('downloaded_at', sa.DateTime(), nullable=True, comment='下载完成时间'), schema='textloom_core')
    op.add_column('media_items', sa.Column('uploaded_at', sa.DateTime(), nullable=True, comment='上传完成时间'), schema='textloom_core')
    op.add_column('media_items', sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'), schema='textloom_core')
    op.drop_index(op.f('idx_sub_video_tasks_sub_task_id'), table_name='sub_video_tasks', schema='textloom_core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_sub_video_tasks_sub_task_id'), 'sub_video_tasks', ['sub_task_id'], unique=True, schema='textloom_core')
    op.drop_column('media_items', 'error_message', schema='textloom_core')
    op.drop_column('media_items', 'uploaded_at', schema='textloom_core')
    op.drop_column('media_items', 'downloaded_at', schema='textloom_core')
    op.drop_column('media_items', 'upload_status', schema='textloom_core')
    op.drop_column('media_items', 'download_status', schema='textloom_core')
    op.drop_column('media_items', 'cloud_url', schema='textloom_core')
    op.drop_column('media_items', 'local_path', schema='textloom_core')
    op.create_index(op.f('idx_material_analyses_task_original_url'), 'material_analyses', ['task_id', 'original_url'], unique=True, schema='textloom_core')
    # ### end Alembic commands ###
