"""remove multi-video fields from tasks table

Revision ID: bb0347984f23
Revises: b7e36c1ff1a7
Create Date: 2025-11-24 09:17:29.107524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb0347984f23'
down_revision: Union[str, Sequence[str], None] = 'b7e36c1ff1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_material_analyses_task_original_url'), table_name='material_analyses', schema='textloom_core')
    op.drop_index(op.f('idx_sub_video_tasks_sub_task_id'), table_name='sub_video_tasks', schema='textloom_core')
    op.drop_column('tasks', 'sub_videos_completed', schema='textloom_core')
    op.drop_column('tasks', 'multi_video_count', schema='textloom_core')
    op.drop_column('tasks', 'multi_video_urls', schema='textloom_core')
    op.drop_column('tasks', 'multi_video_results', schema='textloom_core')
    op.drop_column('tasks', 'is_multi_video_task', schema='textloom_core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_multi_video_task', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否为多视频任务'), schema='textloom_core')
    op.add_column('tasks', sa.Column('multi_video_results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='多视频生成结果列表'), schema='textloom_core')
    op.add_column('tasks', sa.Column('multi_video_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='多个视频URL列表'), schema='textloom_core')
    op.add_column('tasks', sa.Column('multi_video_count', sa.INTEGER(), autoincrement=False, nullable=True, comment='视频生成数量'), schema='textloom_core')
    op.add_column('tasks', sa.Column('sub_videos_completed', sa.INTEGER(), autoincrement=False, nullable=True, comment='已完成的子视频数量'), schema='textloom_core')
    op.create_index(op.f('idx_sub_video_tasks_sub_task_id'), 'sub_video_tasks', ['sub_task_id'], unique=True, schema='textloom_core')
    op.create_index(op.f('idx_material_analyses_task_original_url'), 'material_analyses', ['task_id', 'original_url'], unique=True, schema='textloom_core')
    # ### end Alembic commands ###
