"""add sub_video_tasks columns for two-phase video merge

Revision ID: c9c7a666f577
Revises: ab1756f34899
Create Date: 2025-08-11 19:31:21.361878

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9c7a666f577"
down_revision: Union[str, Sequence[str], None] = "ab1756f34899"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sub_video_tasks",
        sa.Column(
            "sub_task_id", sa.String(length=255), nullable=False, comment="子任务业务ID"
        ),
        schema="textloom_core",
    )
    op.add_column(
        "sub_video_tasks",
        sa.Column(
            "progress", sa.Integer(), nullable=False, comment="子任务进度(0-100)"
        ),
        schema="textloom_core",
    )
    op.add_column(
        "sub_video_tasks",
        sa.Column(
            "script_style", sa.String(length=50), nullable=True, comment="脚本风格"
        ),
        schema="textloom_core",
    )
    op.add_column(
        "sub_video_tasks",
        sa.Column("script_id", sa.UUID(), nullable=True, comment="脚本ID"),
        schema="textloom_core",
    )
    op.add_column(
        "sub_video_tasks",
        sa.Column("script_data", sa.JSON(), nullable=True, comment="脚本/请求快照"),
        schema="textloom_core",
    )
    op.create_unique_constraint(
        None, "sub_video_tasks", ["sub_task_id"], schema="textloom_core"
    )
    # 为脚本内容新增 scenes 列
    op.add_column(
        "script_contents",
        sa.Column("scenes", sa.JSON(), nullable=True, comment="场景列表"),
        schema="textloom_core",
    )
    # 为媒体表新增 resolution 列（若存在则跳过）
    try:
        op.add_column(
            "media_items",
            sa.Column(
                "resolution", sa.String(length=20), nullable=True, comment="分辨率"
            ),
            schema="textloom_core",
        )
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sub_video_tasks", schema="textloom_core", type_="unique")
    op.drop_column("sub_video_tasks", "script_data", schema="textloom_core")
    op.drop_column("sub_video_tasks", "script_id", schema="textloom_core")
    op.drop_column("sub_video_tasks", "script_style", schema="textloom_core")
    op.drop_column("sub_video_tasks", "progress", schema="textloom_core")
    op.drop_column("sub_video_tasks", "sub_task_id", schema="textloom_core")
    # 回滚脚本内容的 scenes 列
    op.drop_column("script_contents", "scenes", schema="textloom_core")
    # 回滚媒体表的 resolution 列
    try:
        op.drop_column("media_items", "resolution", schema="textloom_core")
    except Exception:
        pass
    # ### end Alembic commands ###
