"""add api key support to users table

Revision ID: da536ca717f2
Revises: 8b9d6ff77653
Create Date: 2025-08-22 22:08:06.016543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da536ca717f2'
down_revision: Union[str, Sequence[str], None] = '8b9d6ff77653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_material_analyses_task_original_url'), table_name='material_analyses', schema='textloom_core')
    op.drop_index(op.f('idx_sub_video_tasks_sub_task_id'), table_name='sub_video_tasks', schema='textloom_core')
    op.add_column('users', sa.Column('api_key', sa.String(length=255), nullable=True, comment='API密钥，用于第三方系统认证'), schema='textloom_core')
    op.add_column('users', sa.Column('api_key_enabled', sa.Boolean(), nullable=True, comment='是否启用API密钥认证'), schema='textloom_core')
    op.add_column('users', sa.Column('user_type', sa.String(length=50), nullable=True, comment='用户类型：api_user/admin_user'), schema='textloom_core')
    op.add_column('users', sa.Column('api_quota_limit', sa.Integer(), nullable=True, comment='API调用配额限制（每月）'), schema='textloom_core')
    op.add_column('users', sa.Column('api_quota_used', sa.Integer(), nullable=True, comment='已使用的API调用次数（当月）'), schema='textloom_core')
    op.add_column('users', sa.Column('quota_reset_at', sa.DateTime(), nullable=True, comment='配额重置时间'), schema='textloom_core')
    op.create_unique_constraint(None, 'users', ['api_key'], schema='textloom_core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='textloom_core', type_='unique')
    op.drop_column('users', 'quota_reset_at', schema='textloom_core')
    op.drop_column('users', 'api_quota_used', schema='textloom_core')
    op.drop_column('users', 'api_quota_limit', schema='textloom_core')
    op.drop_column('users', 'user_type', schema='textloom_core')
    op.drop_column('users', 'api_key_enabled', schema='textloom_core')
    op.drop_column('users', 'api_key', schema='textloom_core')
    op.create_index(op.f('idx_sub_video_tasks_sub_task_id'), 'sub_video_tasks', ['sub_task_id'], unique=True, schema='textloom_core')
    op.create_index(op.f('idx_material_analyses_task_original_url'), 'material_analyses', ['task_id', 'original_url'], unique=True, schema='textloom_core')
    # ### end Alembic commands ###
